# This is a basic workflow to help you get started with Actions
name: Releases
# Controls when the workflow will run. It is recommended to run it when a pull request is
# opened and when the pull request code is updated (synchronized)
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - "main"
permissions:
  pull-requests: write # Needed to add comments to the Pull Request that triggered the build
  actions: write # Needed to cancel a workflow when it no longer needs to run
  

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  releases:
    name: release apk
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "3.13.2"
    steps:
      # - uses: actions/checkout@v2
      # - uses: actions/setup-java@v1
      #   with:
      #     java-version: "11.0"
      # - uses: subosito/flutter-action@v1
      #   with:
      #     flutter-version: "3.19.2"
      # - run: flutter pub get
      # - run: flutter analyze
      # - run: flutter test
      # - run: flutter build apk --release
      # Add a step to upload the preview to quill
      - uses: quilldevtools/quill-flutter-action@main
        with:
          app-path: "build/app/outputs/flutter-apk/app-release.apk"
          pkg-name: "com.example.flutter_calculator"
          api-key: "a2eb0e1b-647f-11ef-9627-0242ac120003"
